### ISSUE TITLE
Erro rodando rollback de health_plan

### ISSUE THREAD

**Issue by joaomarcuscardoso** [marquescauee/gerenciaConsultorio#2]
Existe dois errors no drop de health_plan e health_plans_patients, um deles seria a falta de cascade e o outro seria o nome da tabela está errado no create, então o drop teria que seguir o mesmo nome.
Vou alterar direto na migration, o nome da tabela que está em drop isso é correto?
Vou criar uma novas migrations pra renomear a tabela e colocar no padrão
@marquescauee

**Comment by marquescauee** [comment]
sim @joaomarcuscardoso , faltou validar os drops. Além disso, precisa colocar os delete cascades em todas as chaves estrangeiras das tabelas, acabei esquecendo

**Comment by joaomarcuscardoso** [comment]
vou enviar uma pr, não sei se é o melhor jeito de fazer, me avisa se precisar mudar
